import Link from "next/link";
import { LocalServiceArea, phone, ProjectShowcase, SiteFooter, SiteHeader } from "./components";

const services = [
  { number: "01", title: "Dépannage et réparation", description: "Un ordinateur qui rame, un écran bleu ou un PC qui ne démarre plus? On trouve la vraie cause, puis on règle le problème.", icon: "↗", href: "/depannage-informatique-nicolet", image: "/AIP-reparation-informatique.png", imageAlt: "Patrick Potvin répare un ordinateur depuis son bureau à domicile à Nicolet" },
  { number: "02", title: "Virus et cybersécurité", description: "Suppression des logiciels malveillants, nettoyage complet et protection de vos fichiers, sans mauvaises surprises.", icon: "◈", href: "/suppression-virus", image: "/AIP-bureau-informatique.png", imageAlt: "Patrick Potvin vérifie la sécurité et élimine les logiciels malveillants" },
  { number: "03", title: "Assistance à distance", description: "Une solution rapide et sécurisée, directement chez vous. Rien de compliqué à installer après l’intervention.", icon: "⌘", href: "/assistance-informatique-a-distance", image: "/AIP-appel-client.png", imageAlt: "Patrick Potvin accompagne un client à distance depuis son bureau à domicile" },
  { number: "04", title: "Installation et transfert", description: "Nouveau PC, imprimante, Windows ou transfert de données : tout fonctionne comme il faut, dès le départ.", icon: "⇄", href: "/installation-ordinateur-transfert-donnees", image: "/AIP-travail-ordinateur.png", imageAlt: "Patrick Potvin configure un nouvel ordinateur et transfère les données" },
  { number: "05", title: "Réseau et sauvegardes", description: "Un Wi-Fi fiable, des appareils bien connectés et des copies de sécurité pour ne plus craindre de tout perdre.", icon: "⌁", href: "/configuration-wifi-sauvegarde", image: "/AIP-bureau-informatique.png", imageAlt: "Patrick Potvin configure un routeur et une sauvegarde informatique" },
  { number: "06", title: "Sites web sur mesure", description: "Un site élégant, rapide et bien référencé pour votre entreprise. Conçu ici, pour les gens d’ici.", icon: "✳", href: "/creation-sites-web", image: "/AIP-travail-ordinateur.png", imageAlt: "Patrick Potvin présente le site web sur mesure Les Bois Morphée" },
];

export default function Home() {
  return (
    <main>
      <SiteHeader />
      <section className="hero-clean" id="accueil">
        <img className="hero-clean-bg" src="/images/hero-aip-clean.png" alt="" aria-hidden="true" />
        <div className="hero-clean-overlay">
          <img className="hero-clean-logo" src="/images/logo-aip.png" alt="AIP" />
          <div className="hero-clean-brand">ATELIER INFORMATIQUE <strong>POTVIN</strong></div>
          <div className="hero-clean-location">● &nbsp; NICOLET · BÉCANCOUR · TROIS-RIVIÈRES</div>
          <h1>Informatique &amp; Web<span>.</span></h1>
          <h2>Des solutions qui<br />fonctionnent.</h2>
          <p>Dépannage, services informatiques et création<br className="desktop-only" /> de sites web sur mesure. Un seul interlocuteur,<br className="desktop-only" /> des solutions simples et efficaces.</p>
          <div className="hero-clean-actions">
            <a className="hero-clean-primary" href="tel:+18193802999">Discuter de votre projet <span>→</span></a>
            <a className="hero-clean-secondary" href="#services">Découvrir<br />les services <span>↓</span></a>
          </div>
          <div className="hero-clean-trust"><span className="stars">★★★★★</span> 5,0 sur Google · 10 avis <b></b> <span>👤</span> 40 ans d’expérience</div>
        </div>
      </section>
      <section className="metrics"><div className="shell metrics-grid"><div><strong>40 ans</strong><span>d’expérience sur le terrain</span></div><div><strong>50 km</strong><span>de service à domicile</span></div><div><strong>5,0 <i>★</i></strong><span>sur Google, 10 avis</span></div><div><strong>1 seul</strong><span>interlocuteur, du début à la fin</span></div></div></section>
      <section className="services section shell" id="services"><div className="section-heading"><div><div className="eyebrow"><span></span> Deux expertises, clairement séparées</div><h2>Informatique ou Web.<br /><em>Choisissez votre besoin.</em></h2></div><p>Besoin de régler un problème informatique ou de bâtir une présence web professionnelle? Chaque service a son propre parcours, sans confusion.</p></div><img className="services-aip-visual" src="/services-aip.png" alt="Six services Atelier Informatique Potvin : dépannage et réparation, cybersécurité, assistance à distance, installation et transfert, réseau et sauvegardes, sites web sur mesure" /><div className="services-mobile-grid">{services.map(service => <article className="service-mobile-card" key={service.href}><img src={service.image} alt={service.imageAlt} loading="lazy" /><div className="service-mobile-copy"><span>{service.number}</span><h3>{service.title}</h3><p>{service.description}</p><Link href={service.href}>En savoir plus <b>→</b></Link></div></article>)}</div></section>
      <section className="web-focus section shell" id="web"><img className="creation-web-aip-visual" src="/creation-web-aip.png" alt="Création Web AIP : sites professionnels, e-commerce et CMS, solutions sur mesure" /><div className="web-mobile-grid"><article><img src="/AIP-travail-ordinateur.png" alt="Création d’un site web professionnel" /><span>01</span><h3>Sites professionnels</h3><p>Sites vitrines rapides et adaptés au mobile pour présenter votre entreprise et générer des contacts.</p><Link href="/creation-sites-web">Découvrir <b>→</b></Link></article><article><img src="/projet-envol-enfants.png" alt="Boutique e-commerce et CMS sur mesure" /><span>02</span><h3>E-commerce &amp; CMS</h3><p>Boutiques en ligne et interfaces de gestion adaptées aux opérations réelles de votre entreprise.</p><Link href="/creation-sites-web">Parler de votre projet <b>→</b></Link></article><article><img src="/projet-bois-morphee.webp" alt="Solution web conçue sur mesure" /><span>03</span><h3>Solutions sur mesure</h3><p>Automatisation, outils internes et fonctionnalités développées autour de vos besoins.</p><Link href="/creation-sites-web">Découvrir les possibilités <b>→</b></Link></article></div></section>
      <ProjectShowcase />
      <section className="approach section" id="approche"><div className="shell approach-inner"><div className="approach-copy"><div className="eyebrow"><span></span> Un service vraiment humain</div><h2>Pas de jargon.<br /><em>Pas de détour.</em></h2><p>Depuis 40 ans, j’aide les gens de ma région à se sentir en confiance avec leur informatique. Je vous explique ce qui se passe, ce que ça coûte et ce qu’on peut faire — avant de commencer.</p><a className="button button-lime" href="tel:+18193802999">On en parle? <span>↗</span></a></div><div className="approach-steps"><div><span>01</span><h3>Vous m’expliquez.</h3><p>Au téléphone, simplement, dans vos mots.</p></div><div><span>02</span><h3>Je trouve la cause.</h3><p>Un diagnostic clair, avec un prix annoncé d’avance.</p></div><div><span>03</span><h3>On règle ça ensemble.</h3><p>Chez vous, depuis chez moi ou à distance, selon vos besoins.</p></div></div></div></section>
      <section className="pricing section shell" id="tarifs"><div className="section-heading"><div><div className="eyebrow"><span></span> Des prix clairs, tout simplement</div><h2>Les bons tarifs.<br /><em>Sans surprise.</em></h2></div><p>Le montant exact est toujours confirmé après le diagnostic. Voici un bon point de départ.</p></div><div className="pricing-group"><div className="pricing-group-heading"><span>01</span><div><h3>Services informatiques</h3><p>Diagnostic, réparation, configuration, optimisation et assistance à distance.</p></div></div><div className="pricing-grid pricing-grid-two"><article className="price-card"><span>Diagnostic</span><strong>60 $</strong><p>Évaluation complète et soumission claire. Le diagnostic est crédité si vous faites effectuer la réparation.</p></article><article className="price-card"><span>Service informatique</span><strong>60 $<small> / h</small></strong><p>Réparation, configuration, optimisation, installation et assistance à distance.</p></article></div></div><div className="pricing-group pricing-group-web"><div className="pricing-group-heading"><span>02</span><div><h3>Création de sites Web</h3><p>Des forfaits adaptés à la portée réelle de votre projet.</p></div></div><div className="pricing-grid"><article className="price-card"><span>Site essentiel</span><strong>1 500 $<small> +</small></strong><p>Site vitrine professionnel simple pour présenter votre entreprise et générer des contacts.</p></article><article className="price-card"><span>Site professionnel</span><strong>2 500 $<small> +</small></strong><p>Site sur mesure avec identité visuelle, contenu, SEO local et conversion.</p></article><article className="price-card"><span>Site signature</span><strong>4 000 $<small> +</small></strong><p>Projet complet avec stratégie, contenu, visuels personnalisés et réalisations.</p></article><article className="price-card"><span>Commerce / CMS / outil Web</span><strong>5 000 $<small> +</small></strong><p>E-commerce, administration personnalisée, automatisations et fonctionnalités métier.</p></article></div></div></section>
      <section className="reviews section"><div className="shell"><div className="section-heading"><div><div className="eyebrow"><span></span> Ce que mes clients en disent</div><h2>De vraies personnes.<br /><em>De vrais résultats.</em></h2></div><p>Une note de 5,0 sur Google, grâce à dix avis de clients de la région.</p></div><div className="reviews-grid"><article><div className="stars">★★★★★</div><blockquote>« Service impeccable. Je recommande fortement ses services, il est expert dans son domaine. »</blockquote><span>Alex Therrien</span></article><article><div className="stars">★★★★★</div><blockquote>« Un gros problème de micro, j’ai gossé dessus pendant deux mois, il a trouvé le problème en 10 minutes. »</blockquote><span>Etienne Therrien</span></article><article><div className="stars">★★★★★</div><blockquote>« Service dépannage au top. Service hors pair pour résoudre mon problème, avec un langage clair et de l’humour. »</blockquote><span>Solange Poulin</span></article></div></div></section>
      <LocalServiceArea />
      <section className="contact section" id="contact"><div className="shell contact-inner"><div><div className="eyebrow"><span></span> On règle ça ensemble</div><h2>Un souci informatique?<br /><em>Appelez-moi.</em></h2><p>Pas de formulaire compliqué. Pas de robot. Juste Patrick, qui prend le temps de comprendre votre problème.</p></div><div className="contact-card"><span>Joignez-moi directement</span><a className="big-phone" href="tel:+18193802999">819 380-2999</a><p>462, rue D. N. St-Cyr<br />Nicolet (Québec) J3T 1H3</p><div className="response-note"><span></span>Réponse habituellement dans la journée</div><a className="button button-lime" href="tel:+18193802999">Appeler maintenant <span>↗</span></a></div></div></section>
      <SiteFooter />
    </main>
  );
}
