import Link from "next/link";
import { LocalServiceArea, phone, ProjectShowcase, SiteFooter, SiteHeader } from "./components";

const services = [
  { number: "01", title: "Dépannage et réparation", description: "Un ordinateur qui rame, un écran bleu ou un PC qui ne démarre plus? On trouve la vraie cause, puis on règle le problème.", icon: "↗", href: "/depannage-informatique-nicolet", image: "/service-depannage.webp", imageAlt: "Patrick Potvin répare un ordinateur depuis son bureau à domicile à Nicolet" },
  { number: "02", title: "Virus et cybersécurité", description: "Suppression des logiciels malveillants, nettoyage complet et protection de vos fichiers, sans mauvaises surprises.", icon: "◈", href: "/suppression-virus", image: "/service-cybersecurite.webp", imageAlt: "Patrick Potvin vérifie la sécurité et élimine les logiciels malveillants" },
  { number: "03", title: "Assistance à distance", description: "Une solution rapide et sécurisée, directement chez vous. Rien de compliqué à installer après l’intervention.", icon: "⌘", href: "/assistance-informatique-a-distance", image: "/service-assistance-distance.webp", imageAlt: "Patrick Potvin accompagne un client à distance depuis son bureau à domicile" },
  { number: "04", title: "Installation et transfert", description: "Nouveau PC, imprimante, Windows ou transfert de données : tout fonctionne comme il faut, dès le départ.", icon: "⇄", href: "/installation-ordinateur-transfert-donnees", image: "/service-installation-transfert.webp", imageAlt: "Patrick Potvin configure un nouvel ordinateur et transfère les données" },
  { number: "05", title: "Réseau et sauvegardes", description: "Un Wi-Fi fiable, des appareils bien connectés et des copies de sécurité pour ne plus craindre de tout perdre.", icon: "⌁", href: "/configuration-wifi-sauvegarde", image: "/service-reseau-sauvegardes.webp", imageAlt: "Patrick Potvin configure un routeur et une sauvegarde informatique" },
  { number: "06", title: "Sites web sur mesure", description: "Un site élégant, rapide et bien référencé pour votre entreprise. Conçu ici, pour les gens d’ici.", icon: "✳", href: "/creation-sites-web", image: "/service-sites-web.webp", imageAlt: "Patrick Potvin présente le site web sur mesure Les Bois Morphée" },
];

export default function Home() {
  return (
    <main>
      <SiteHeader />
      <section className="hero shell" id="accueil">
        <div className="hero-copy"><div className="eyebrow"><span></span> Nicolet · Centre-du-Québec</div><h1>Informatique & Web.<br /><span>Des solutions qui fonctionnent.</span></h1><p>Deux expertises, un seul interlocuteur : dépannage et services informatiques d’un côté, création de sites web et solutions numériques sur mesure de l’autre.</p><div className="hero-actions"><a className="button button-dark" href="tel:+18193802999">Discuter de votre projet <span>↗</span></a><a className="text-link" href="#services">Découvrir les services <span>↓</span></a></div><div className="trust-line"><div className="stars">★★★★★</div><span>5,0 sur Google · 10 avis</span><i></i><span>40 ans d’expérience</span></div></div>
        <div className="hero-portrait"><img src="/patrick-atelier-hero.webp" alt="Patrick Potvin dans son espace de travail à la maison à Nicolet" /><div className="portrait-note"><span className="note-dot"></span><span>Patrick Potvin<br /><strong>Votre technicien de confiance</strong></span></div></div>
      </section>
      <section className="metrics"><div className="shell metrics-grid"><div><strong>40 ans</strong><span>d’expérience sur le terrain</span></div><div><strong>50 km</strong><span>de service à domicile</span></div><div><strong>5,0 <i>★</i></strong><span>sur Google, 10 avis</span></div><div><strong>1 seul</strong><span>interlocuteur, du début à la fin</span></div></div></section>
      <section className="services section shell" id="services"><div className="section-heading"><div><div className="eyebrow"><span></span> Deux expertises, clairement séparées</div><h2>Informatique ou Web.<br /><em>Choisissez votre besoin.</em></h2></div><p>Besoin de régler un problème informatique ou de bâtir une présence web professionnelle? Chaque service a son propre parcours, sans confusion.</p></div><div className="services-grid">{services.map((service) => <article className="service-card" key={service.number}><Link className="service-card-photo" href={service.href} aria-label={service.title}><img src={service.image} alt={service.imageAlt} loading="lazy" /></Link><div className="service-card-content"><div className="card-top"><span>{service.number}</span><span className="service-icon">{service.icon}</span></div><h3>{service.title}</h3><p>{service.description}</p><Link className="service-card-link" href={service.href}>En savoir plus <span>→</span></Link></div></article>)}</div></section>
      <section className="workshop section"><div className="shell"><div className="section-heading"><div><div className="eyebrow"><span></span> Un service local et personnel</div><h2>Du vrai travail.<br /><em>Des solutions concrètes.</em></h2></div><p>Dépannage informatique et création web sont deux expertises distinctes, prises en charge personnellement du diagnostic jusqu’à la livraison.</p></div><div className="workshop-gallery"><figure><img src="/service-depannage.webp" alt="Patrick Potvin répare un ordinateur depuis son bureau à domicile à Nicolet" loading="lazy" /><figcaption><span>01</span>Diagnostic et réparation informatique</figcaption></figure><figure><img src="/service-sites-web.webp" alt="Patrick Potvin conçoit un site web professionnel depuis son bureau à la maison" loading="lazy" /><figcaption><span>02</span>Création de sites web sur mesure</figcaption></figure></div></div></section>
      <section className="web-focus section shell" id="web"><div className="section-heading"><div><div className="eyebrow"><span></span> Création Web</div><h2>Votre entreprise.<br /><em>Votre outil numérique.</em></h2></div><p>Sites vitrines, boutiques en ligne, CMS et outils sur mesure : des solutions conçues pour être utiles, rapides et simples à gérer.</p></div><div className="web-focus-grid"><article><span>01</span><h3>Sites professionnels</h3><p>Une présence claire, moderne et optimisée pour transformer les visites en prises de contact.</p><Link href="/creation-sites-web">Voir le service <span>→</span></Link></article><article><span>02</span><h3>E-commerce & CMS</h3><p>Boutiques en ligne et interfaces de gestion adaptées aux opérations réelles de votre entreprise.</p><Link href="/creation-sites-web">Parler de votre projet <span>→</span></Link></article><article><span>03</span><h3>Solutions sur mesure</h3><p>Automatisation, outils internes et fonctionnalités développées autour de vos besoins plutôt qu’un modèle générique.</p><Link href="/creation-sites-web">Découvrir les possibilités <span>→</span></Link></article></div></section>
      <ProjectShowcase />
      <section className="approach section" id="approche"><div className="shell approach-inner"><div className="approach-copy"><div className="eyebrow"><span></span> Un service vraiment humain</div><h2>Pas de jargon.<br /><em>Pas de détour.</em></h2><p>Depuis 40 ans, j’aide les gens de ma région à se sentir en confiance avec leur informatique. Je vous explique ce qui se passe, ce que ça coûte et ce qu’on peut faire — avant de commencer.</p><a className="button button-lime" href="tel:+18193802999">On en parle? <span>↗</span></a></div><div className="approach-steps"><div><span>01</span><h3>Vous m’expliquez.</h3><p>Au téléphone, simplement, dans vos mots.</p></div><div><span>02</span><h3>Je trouve la cause.</h3><p>Un diagnostic clair, avec un prix annoncé d’avance.</p></div><div><span>03</span><h3>On règle ça ensemble.</h3><p>Chez vous, depuis chez moi ou à distance, selon vos besoins.</p></div></div></div></section>
      <section className="pricing section shell" id="tarifs"><div className="section-heading"><div><div className="eyebrow"><span></span> Des prix clairs, tout simplement</div><h2>Les bons tarifs.<br /><em>Sans surprise.</em></h2></div><p>Le montant exact est toujours confirmé après le diagnostic. Voici un bon point de départ.</p></div><div className="pricing-grid"><article className="price-card"><span>Diagnostic</span><strong>45 $</strong><p>Évaluation complète et soumission claire. Gratuit si vous faites effectuer la réparation.</p></article><article className="price-card featured"><span>Assistance à distance</span><strong>50 $</strong><p>Par séance, jusqu’à 45 minutes. Idéal pour les problèmes courants sans déplacement.</p></article><article className="price-card"><span>Taux horaire</span><strong>65 $<small> / h</small></strong><p>Réparation, optimisation et configuration, à votre domicile ou à distance.</p></article><article className="price-card"><span>Site web vitrine</span><strong>1 500 $<small> +</small></strong><p>Une présence professionnelle conçue sur mesure pour votre entreprise locale.</p></article></div></section>
      <section className="reviews section"><div className="shell"><div className="section-heading"><div><div className="eyebrow"><span></span> Ce que mes clients en disent</div><h2>De vraies personnes.<br /><em>De vrais résultats.</em></h2></div><p>Une note de 5,0 sur Google, grâce à dix avis de clients de la région.</p></div><div className="reviews-grid"><article><div className="stars">★★★★★</div><blockquote>« Service impeccable. Je recommande fortement ses services, il est expert dans son domaine. »</blockquote><span>Alex Therrien</span></article><article><div className="stars">★★★★★</div><blockquote>« Un gros problème de micro, j’ai gossé dessus pendant deux mois, il a trouvé le problème en 10 minutes. »</blockquote><span>Etienne Therrien</span></article><article><div className="stars">★★★★★</div><blockquote>« Service dépannage au top. Service hors pair pour résoudre mon problème, avec un langage clair et de l’humour. »</blockquote><span>Solange Poulin</span></article></div></div></section>
      <LocalServiceArea />
      <section className="contact section" id="contact"><div className="shell contact-inner"><div><div className="eyebrow"><span></span> On règle ça ensemble</div><h2>Un souci informatique?<br /><em>Appelez-moi.</em></h2><p>Pas de formulaire compliqué. Pas de robot. Juste Patrick, qui prend le temps de comprendre votre problème.</p></div><div className="contact-card"><span>Joignez-moi directement</span><a className="big-phone" href="tel:+18193802999">819 380-2999</a><p>462, rue D. N. St-Cyr<br />Nicolet (Québec) J3T 1H3</p><div className="response-note"><span></span>Réponse habituellement dans la journée</div><a className="button button-lime" href="tel:+18193802999">Appeler maintenant <span>↗</span></a></div></div></section>
      <SiteFooter />
    </main>
  );
}
