import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../components";
import { jsonLd, pageMetadata } from "../seo";

export const metadata: Metadata = pageMetadata({ title: "FAQ informatique Nicolet | Dépannage, prix, Wi-Fi et Web", description: "Questions fréquentes sur le dépannage informatique à Nicolet : tarifs, service à domicile, assistance à distance, virus, Wi-Fi, sauvegardes, transfert de données et création de sites web.", path: "/faq", image: "/aip-travail-02.webp" });
const questions = [
  ["Combien coûte un diagnostic?", "Le diagnostic est de 60 $ et il est crédité si vous faites effectuer la réparation. Une estimation claire est donnée avant de poursuivre."],
  ["Quel est votre tarif pour le dépannage informatique?", "Le service informatique est facturé 60 $ / h pour la réparation, l’optimisation, la configuration, l’installation et l’assistance à distance."],
  ["En combien de temps vais-je recevoir une réponse?", "Patrick répond habituellement dans la journée. Le délai exact peut varier selon les interventions en cours et le moment de votre appel."],
  ["Faites-vous du service à domicile?", "Oui. Le service à domicile couvre un rayon d’environ 50 km autour de Nicolet, notamment Bécancour et Trois-Rivières."],
  ["Quelles régions desservez-vous?", "Le service couvre principalement Nicolet, Bécancour, Trois-Rivières et les municipalités situées à environ 50 km de Nicolet. Les projets web et certaines interventions peuvent aussi être réalisés à distance."],
  ["Pouvez-vous réparer mon ordinateur à distance?", "Souvent, oui. Si l’ordinateur se connecte encore à Internet, plusieurs problèmes de Windows, de logiciels, de courriel, d’imprimante ou de configuration peuvent être réglés à distance."],
  ["Que se passe-t-il si ma connexion Internet ne fonctionne plus?", "Une intervention à distance n’est alors pas possible. Selon votre emplacement et le problème, un dépannage à domicile peut être envisagé."],
  ["Est-ce sécuritaire de vous donner accès à mon ordinateur à distance?", "La connexion doit être autorisée pour l’intervention. Vous voyez les manipulations à l’écran et vous pouvez mettre fin à la séance. L’accès est limité aux éléments nécessaires au dépannage."],
  ["Quels signes peuvent indiquer un virus ou un logiciel malveillant?", "Des fenêtres publicitaires inhabituelles, de faux avertissements, des redirections, des extensions inconnues ou des lenteurs soudaines peuvent justifier une vérification."],
  ["Que dois-je faire si je pense que mon ordinateur est infecté?", "Évitez les opérations sensibles, notamment bancaires, jusqu’à ce que la situation soit vérifiée. Une intervention peut ensuite servir à détecter et supprimer les logiciels malveillants et à sécuriser le système."],
  ["Pouvez-vous configurer un nouvel ordinateur?", "Oui. La mise en route peut inclure Windows, les mises à jour, le compte utilisateur, le navigateur, les paramètres utiles, les logiciels nécessaires et les périphériques selon votre situation."],
  ["Pouvez-vous transférer mes photos et mes documents vers un nouveau PC?", "Oui, lorsque les données de l’ancien ordinateur ou de son disque restent accessibles. Les fichiers importants peuvent être copiés et organisés sur le nouvel ordinateur."],
  ["Mes logiciels seront-ils automatiquement transférés sur mon nouveau PC?", "Pas nécessairement. Les fichiers peuvent être copiés, mais les logiciels doivent généralement être réinstallés. Les licences, mots de passe et accès nécessaires doivent être disponibles."],
  ["Pouvez-vous récupérer mes fichiers si mon ancien ordinateur ne démarre plus?", "Cela dépend de l’état de l’ordinateur et du disque. Un diagnostic permet de déterminer si les données restent accessibles avant de promettre un résultat."],
  ["Pouvez-vous régler un problème de Wi-Fi ou d’imprimante réseau?", "Oui. Le routeur, la connexion Internet, le signal, les appareils concernés et les paramètres réseau peuvent être vérifiés avant de recommander un changement de matériel."],
  ["Est-ce qu’un nouveau routeur règle toujours un mauvais Wi-Fi?", "Non. L’emplacement du routeur, les obstacles, la configuration et la connexion du fournisseur peuvent aussi être en cause. Il vaut mieux vérifier la situation avant d’acheter du matériel."],
  ["Pouvez-vous m’aider à mettre en place une sauvegarde de mes fichiers?", "Oui. Les documents, photos et autres fichiers importants peuvent être identifiés afin de choisir une méthode de sauvegarde adaptée et de vérifier que les copies sont accessibles."],
  ["Une sauvegarde garantit-elle que je ne perdrai jamais mes données?", "Non. Aucune solution n’élimine tous les risques. L’objectif est d’avoir des copies distinctes, vérifiables et adaptées à l’importance de vos données."],
  ["Mes données restent-elles confidentielles?", "Oui. Vos fichiers sont traités avec discrétion et seulement dans la mesure nécessaire pour effectuer l’intervention."],
  ["Combien de temps prend une réparation?", "Cela dépend du problème et des pièces nécessaires. Après le diagnostic, Patrick vous indique le délai réaliste avant de poursuivre."],
  ["Créez-vous aussi des sites web?", "Oui. Atelier Informatique Potvin conçoit des sites vitrines, des sites professionnels, des boutiques en ligne et des CMS sur mesure pour les entreprises locales ou à distance."],
  ["Combien coûte un site web?", "Un site vitrine de base débute à 900 $. Le prix varie ensuite selon le nombre de pages, le contenu, les intégrations et les fonctionnalités nécessaires. Une estimation est préparée selon votre projet."],
  ["Est-ce que les sites web sont adaptés aux téléphones?", "Oui. Les projets web sont conçus pour offrir une navigation claire et un affichage adapté au téléphone, à la tablette et à l’ordinateur."],
  ["Est-ce que vous vous occupez du référencement Google?", "Les sites sont structurés avec des titres, du contenu et des pages pensés pour aider Google à comprendre les services et les secteurs desservis. Le positionnement dépend ensuite notamment de la concurrence et du contenu."],
  ["Pouvez-vous créer une boutique en ligne ou un CMS?", "Oui. Selon le projet, Atelier Informatique Potvin peut développer une boutique, un catalogue, une administration personnalisée ou des fonctionnalités adaptées au fonctionnement de l’entreprise."],
];

export default function Page(){const faqSchema={"@context":"https://schema.org","@type":"FAQPage",mainEntity:questions.map(([question,answer])=>({"@type":"Question",name:question,acceptedAnswer:{"@type":"Answer",text:answer}}))};return <main><SiteHeader/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLd(faqSchema)}}/><section className="detail-hero detail-hero-photo shell"><div className="detail-hero-copy"><div className="eyebrow"><span></span>Questions fréquentes</div><h1>Des réponses claires.<br/><em>Avant même d’appeler.</em></h1><p>Tarifs, dépannage, service à domicile, assistance à distance, virus, Wi-Fi, sauvegardes, transfert de données et création de sites web : voici les réponses aux questions les plus courantes.</p></div><figure className="detail-photo detail-photo-portrait"><img src="/aip-travail-02.webp" alt="Patrick Potvin, votre technicien informatique à Nicolet" /></figure></section><section className="section faq-section"><div className="shell faq-list">{questions.map(([q,a],i)=><details key={q} open={i===0}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section><section className="contact section"><div className="shell contact-inner"><div><div className="eyebrow"><span></span>Votre question n’est pas ici?</div><h2>Parlez directement<br/><em>à Patrick.</em></h2></div><div className="contact-card"><span>Appelez maintenant</span><a className="big-phone" href="tel:+18193802999">819 380-2999</a><p>Nicolet, Bécancour et Trois-Rivières</p></div></div></section><SiteFooter/></main>}
